#!/bin/bash

set +x

# sla: the Simple Little Automator.
#
# A replacement for 'make' for projects that don't require incremental
# compilation, such as scripting languages.
#
# Author: Ferry Boender
# Homepage: https://github.com/fboender/sla
# License: MIT
#
# Copyright (c) 2022 Ferry Boender
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


VERSION=1.7.1
RULES_FILE="build.sla"

if [ -t 1 ] && [ -n "$TERM" ] && [ "$TERM" != "dumb" ]; then
    # Our output is not being redirected and we have a terminal, so we can use
    # colors.
    C_RED="\033[1;31m"
    C_GREEN="\033[1;32m"
    C_WHITE="\033[1;37m"
    C_RESET="$(tput sgr0)"
fi

#
# Display debug message if FLAG_DEBUG is set (-d, --debug)
#
msg_debug () {
    [ "$FLAG_DEBUG" -eq 1 ] && echo "DEBUG: $*" >&2
}

#
# Print error message to stderr and exit with code 2
#
die () {
    printf "${C_RED}%s$C_RESET\n" "$*" >&2
    exit 2
}

#
# Print okay message to stdout
#
okay () {
    printf "${C_GREEN}%s$C_RESET\n" "$*" >&2
}

#
# Display usage message
#
usage () {
    echo "Usage: sla [-hdv] [--version] <rule> [param [param...]]"
    echo
    echo "Simple Little Automator. Find and execute tasks from a shell script."
    echo
    echo "Arguments:"
    echo "  -h, --help      Show this help message"
    echo "  -d, --debug     Show internal sla debug information"
    echo "  -v, --verbose   Verbose output"
    echo "  -V, --version   Show sla version"
    echo
    echo "If no <rule> is specified, lists the available rules."
    echo
    echo "Use '$0 <rule> --help' to show a rule's full description."
    exit 1
}

#
# Display version
#
version () {
    echo "sla v$VERSION"
    echo "(C) 2022 Ferry Boender - MIT license"
    echo "https://github.com/fboender/sla"
    exit 1
}

#
# Keep going down a directory from the current directory until we find a
# rules file or reach the root dir. Print the directory containing the rules
# file.
#
find_project_root () {
    PROJ_ROOT="$(realpath .)"
    while true; do
        msg_debug "Testing \"$PROJ_ROOT/$RULES_FILE\""
        if [ -f "$PROJ_ROOT/$RULES_FILE" ]; then
            # Found a $RULES_FILE file. Return it
            msg_debug "$RULES_FILE found at $PROJ_ROOT"
            echo "$PROJ_ROOT"
            break
        elif [ "$PROJ_ROOT" = "/" ]; then
            # Reached the root dir. Return empty string.
            echo ""
            break
        else
            # Go one dir up
            PROJ_ROOT="$(realpath "$PROJ_ROOT"/..)"
        fi
    done
}

#
# Print a list of rules found in the rules file
#
get_rules () {
    grep -E '^[^_ #](\w|-)*\s+\(\s*\)\s*\{' "$PROJ_ROOT/$RULES_FILE" | sed "s/^\(.*\)[[:space:]]*(.*/\\1/"
}

#
# Return the line with the first comment inside a rule
#
get_rule_short_desc () {
    RULE="$1"
    DOC_LINE="$(grep -A1 -E "^$RULE\s?\(\)\s?\{" "$PROJ_ROOT/$RULES_FILE" | grep -E "^[ 	]*#")"

    if [ -n "$DOC_LINE" ]; then
        # shellcheck disable=SC2001
        echo "$DOC_LINE" | sed "s/^[ 	]*#[ 	]*//"
    fi
}

#
# Return the first lines with comments inside a rule until an empty line is
# encounted. First line is then stripped.
#
get_rule_full_desc () {
    RULE="$1"
    FUNC_DEF="$(sed -n "/^${RULE}[[:space:]]\+()[[:space:]]\+{[[:space:]]*$/,/^}$/p" "$PROJ_ROOT/$RULES_FILE")"
    #FULL_DESC="$(echo "$FUNC_DEF" | sed '1,2d' | sed -n '/^[[:space:]]\+#.*/p;/^[[:space:]]*$/q' | sed "s/^[ 	]*#[ 	]*/aap/")"
    FULL_DESC="$(echo "$FUNC_DEF" | sed '1,2d' | sed -n '/^[[:space:]]\+#.*/p;/^[[:space:]]*$/q' | sed "s/^[[:space:]]*#//")"
    echo "$FULL_DESC"
}

#
# List rules found in the rules found
#
list_rules () {
    RULES="$(get_rules)"

    echo "Available rules:"
    echo
    for RULE in $RULES; do
        RULE_DESC="$(get_rule_short_desc "$RULE")"
        if [ -z "$RULE_DESC" ]; then
            printf " - ${C_WHITE}%s$C_RESET\n" "$RULE"
        else
            printf " - ${C_WHITE}%s$C_RESET: %s\n" "$RULE" "$RULE_DESC"
        fi
    done
    echo
    echo "Use 'sla <rule> --help' to show a rule's full description."
}

#
# Convert seconds to human readable duration (1h 8m 5s)
#
sec_to_human () {
    SECONDS="$1"
    HOURS=$(( SECONDS / 3600))
    SECONDS=$(( SECONDS % 3600))
    MINUTES=$(( SECONDS / 60))
    SECONDS=$(( SECONDS % 60))
    ELAPSED_TIME="${HOURS}h ${MINUTES}m ${SECONDS}s"
    echo "$ELAPSED_TIME"
}

# Handle commandline arguments
FLAG_DEBUG=0
FLAG_VERBOSE=0
FLAG_SHOW_RULE_DOC=0
RULE=""

while [ -n "$1" ]; do
    case "$1" in
        "-h" | "--help")
            usage
            shift
            ;;
        "-V"|"--version")
            version
            shift
            ;;
        "-d" | "--debug")
            FLAG_DEBUG=1
            shift
            ;;
        "-v" | "--verbose")
            FLAG_VERBOSE=1
            shift
            ;;
        *)
            RULE="$1"
            shift

            case "$1" in
                "-h" | "--help")
                    FLAG_SHOW_RULE_DOC=1
                    shift
                    break
                    ;;
            esac
            break
            ;;
    esac
done

# Find the project root (dir where build.sla is)
PROJ_ROOT="$(find_project_root)"
if [ -z "$PROJ_ROOT" ]; then
    die "No $RULES_FILE found"
fi

# Verify that the build.sla is owned by the current user and not writable for
# others. This probably isn't very POSIX.. but I see no other way.
RULE_OWNER=$(stat -c "%u" "$PROJ_ROOT/$RULES_FILE")
RULE_GROUP=$(stat -c "%g" "$PROJ_ROOT/$RULES_FILE")
USER_ID=$(id -u)
GROUP_ID=$(id -g)
BAD_PERMS="2367"
PERMS=$(stat -c "%a" "$PROJ_ROOT/$RULES_FILE")
WORLD_ACCESS=$(printf "%s" "$PERMS" | tail -c 1)

if [ "$RULE_OWNER" -ne "$USER_ID" ] | [ "$RULE_GROUP" -ne "$GROUP_ID" ]; then
    echo "$RULES_FILE owner/group does not match current user. This is a security risk. Aborting." >&2
    exit 253
fi

if echo "$BAD_PERMS" | grep "$WORLD_ACCESS" > /dev/null; then
    echo "$RULES_FILE has world writable permissions. This is a security risk. Aborting." >&2
    exit 253
fi

if [ -z "$RULE" ]; then
    # List all the rules
    list_rules
    exit 1
fi

if [ "$FLAG_SHOW_RULE_DOC" -eq 1 ]; then
    # Show rule documentation
    SHORT_DESC="$(get_rule_short_desc "$RULE")"
    LONG_DESC="$(get_rule_full_desc "$RULE")"

    if [ -z "$SHORT_DESC" ]; then
        printf "${C_WHITE}%s${C_RESET}: No description\n" "$RULE"
    else
        printf "${C_WHITE}%s${C_RESET}: %s\n" "$RULE" "$SHORT_DESC"
    fi
    if [ -n "$LONG_DESC" ]; then
        printf "\n%s\n\n" "$LONG_DESC" | sed "s/^/    /" 
    fi

    exit 1
fi

# Check that the requested rule exists
get_rules | grep "$RULE" > /dev/null || die "Rule '$RULE' not found"

msg_debug "FLAG_VERBOSE: $FLAG_VERBOSE"
msg_debug "PROJ_ROOT: $PROJ_ROOT"
msg_debug "RULE: $RULE"
msg_debug "PARAMS:" "$@"

# Include and run the requested rule. Runs in subshell so get back exit code if
# execution fails with "set -e"
TIME_START="$(date +"%s")"
(
    # Jump to project root
    cd "$PROJ_ROOT"

    # Source the rules file and execute the requested rule
    # shellcheck source=/dev/null
    source "$PROJ_ROOT/$RULES_FILE"

    if [ "$FLAG_VERBOSE" -eq 1 ]; then
        # Show all commands being execute
        set -x
    fi
    set -e  # Fail on errors immediately
    $RULE "$@"
)
EXIT_CODE=$?
set +x

# Calculate duration
TIME_END="$(date +"%s")"
ELAPSED=$(( TIME_END - TIME_START ))
ELAPSED_HUMAN="$(sec_to_human $ELAPSED)"

if [ $EXIT_CODE -ne 0 ]; then
    die "Execution of rule '$RULE' failed with exitcode $EXIT_CODE. Duration: $ELAPSED_HUMAN"
else
    okay "Execution of rule '$RULE' succeeded with exitcode $EXIT_CODE. Duration: $ELAPSED_HUMAN"
fi
